version: "2"
services:
  zookeeper:
      image: flokkr/zookeeper
      hostname: zookeeper
      environment:
        ZOO.CFG_clientPort: 2181
        ZOO.CFG_dataDir: /tmp/zookeeper
  kafka:
      hostname: kafka
      image: flokkr/kafka
      ports:
        - 9092:9092
      environment:
         SERVER.PROPERTIES!CFG_zookeeper.connect: zookeeper:2181
         SERVER.PROPERTIES!CFG_num.partitions: 1
         SERVER.PROPERTIES!CFG_broker.id: 1
         SERVER.PROPERTIES!CFG_log.dir: /data/kafkalog
         SERVER.PROPERTIES!CFG_offsets.topic.replication.factor: 1
         WAITFOR: zookeeper:2181
  kafkapublisher:
     image: flokkr/kafka
     command: ["bash","-c","'while sleep 5; do date | ./bin/kafka-console-producer.sh --topic test --broker-list kafka:9092; done'"]
     environment:
         SLEEP_SECONDS: 12
  kafkasubscriber:
     image: flokkr/kafka
     command: ["./bin/kafka-console-consumer.sh --topic test --bootstrap-server kafka:9092"]
     environment:
         SLEEP_SECONDS: 10
