
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-demo
    component: producer
  name: kafka-demo-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-demo
      component: producer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka-demo
        component: producer
    spec:
      containers:
      - name: producer
        image: flokkr/kafka:2.5.0
        imagePullPolicy: IfNotPresent
        command:
        - bash
        - -c
        - /scripts/producer.sh
        volumeMounts:
        - mountPath: /scripts
          name: scripts
        - name: smoketest
          mountPath: /opt/smoketest
      volumes:
      - name: scripts
        configMap:
          defaultMode: 493
          name: scripts
      - name: smoketest
        hostPath:
          path: /home/elek/projects/flokkr/docker-kafka/examples/smoketest
